version: '3'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - ./data/mysql/data:/var/lib/mysql
    networks:
      moodlenet:
        ipv4_address: ${MYSQL_HOST} 

  php:
    build:
      context: ./php7-fpm
    image: php7-fpm:moodle
    container_name: php7
    ports:
      - "9000:9000"
    env_file: .env
    volumes:
      - ./data/moodle/moodle:/var/www/html/moodle
      - ./data/moodle/moodledata:/var/www/moodledata
    networks:
      moodlenet:
        ipv4_address: ${PHP_HOST} 

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/moodle/moodle:/var/www/html/moodle
      - ./data/moodle/moodledata:/var/www/moodledata
      - ./logs:/var/log/nginx
    links:
      - php
    depends_on:
      - php
    env_file: .env
    networks:
      moodlenet:
        ipv4_address: ${NGINX_HOST}  


networks:
  moodlenet:
    driver: bridge    
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
