version: '3.4'

services:

  mysqldb:
    image: mysql:latest
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    network_mode: "bridge"
    env_file: .env

  moodle:
    build:
      context: .
      target: moodle
    image: moodle:3.6
    depends_on:
      - mysqldb
    container_name: moodle
    environment:
      APACHE_LOG_DIR: ${APACHE_LOG_DIR}
    ports:
      - "80:80"
    volumes:
      - ./moodle_data:/var/www/moodledata
    network_mode: "bridge"
  

volumes:
  moodle_data:
    driver: local
  mysql_data:
    driver: local